spring.application.name=Trackme
spring.datasource.url=jdbc:postgresql://localhost:5432/trackme_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true